### ISSUE TITLE
NitrokeyManager::get_status() returns an invalid struct (255 for {enable,delete}_user_password)

### ISSUE THREAD

**Issue by robinkrahl** [Nitrokey/libnitrokey#102]
From my understanding, the `enable_user_password` and `delete_user_password` fields in the struct returned by `NitrokeyManager::get_status()` should be either 0 or 1, and their sum should always be one. But I get the value 255 for both fields, which is invalid according to the `isValid()` method.  How should I interpret this? (I’m using a Nitrokey Pro.)

Example code:
```c++
#include <iostream>
#include <libnitrokey/NitrokeyManager.h>

int main()
{
    auto manager = nitrokey::NitrokeyManager::instance();
    if (!manager->connect())
        return 1;

    auto status = manager->get_status();
    std::cout
        << "Enable user password: " << (int) status.enable_user_password << "\n"
        << "Delete user password: " << (int) status.delete_user_password << "\n"
        << "Valid:                " << status.isValid() << "\n";
    return 0;
}
```

Output:
```
Enable user password: 255
Delete user password: 255
Valid:                0
```

**Comment by szszszsz** [comment]
Hi!

Indeed, libnitrokey's `/NK_C_API.h:8` is suggesting, that these two should complement each other. Actually this is not true and `delete_user_password` is unused/reserved at the moment. I will correct the validation function and mark the field as reserved - thank you for catching that!

As for the value, Pro checks whether `enable_user_password == 1` (`keyboard/report_protocol.c:276`) and if this is true, it enables PIN protection. Implementation relies on bool to int compiler's cast to get the `1` value, so that too will be corrected too.

Back to the `delete_user_password`: I have checked the Pro's v0.8 firmware - `keyboard/report_protocol.c:287` - and there the byte is copied as is to the output but never used internally. So at the moment you could store any single-byte value there (with `write_config`) and it will be copied back on each status request.

**Comment by szszszsz** [comment]
- [ ] Precise bool to int, NitrokeyManager.cc:846
- [ ] Correct C API documentation, /NK_C_API.h:8
- [ ] Correct validation function, include/stick10_commands.h:391

**Comment by robinkrahl** [comment]
Thanks for the explanation!

On a related note: I have some points that are not really bugs, but feature requests or implementation details that would make it easier to use the library. Are you interested in such feedback? If yes, where would be the best place (GitHub, forum, mail)?

**Comment by szszszsz** [comment]
Sure! All feedback is welcomed, if not desired. Best place for mentioned bugs, features requests or working code submission is Github, where each could be discussed, labeled and perhaps included into release plans by setting its milestone. General rule is that API functions change or deletion is done each major release (as 3 in 3.x) and features addition each minor (as 1 in x.1). 
Forum is designated for support, as in responding to general questions, requests for tutorials or just explaining topics. If not sure, then shoot for forum - we could discuss and decide about the problem further.
