### ISSUE TITLE
Doesn't detect Librem Key on Ubuntu 18.04

### ISSUE THREAD

**Issue by knkski** [Nitrokey/libnitrokey#162]
- Application version: `1.4.0snap4` (installed via snap)
- Operating system: `Linux cat 5.0.0-25-generic Nitrokey/nitrokey-app#26~18.04.1-Ubuntu SMP Thu Aug 1 13:51:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
- Device model and firmware version: Librem Key, unknown firmware version
- Connected USB port type:2.0
- Issue occurrency: always

### Expected behaviour

The Nitrokey app detects the Librem Key as a regular Nitrokey. This is expected due to PureOS forum posts talking about using the Nitrokey app with the Librem Key.

### Current behaviour

The Nitrokey app does not detect the Librem Key. This seems to be at least in part due to different USB vendor and product IDs (The Librem Key uses `316d:4c4b`).

### Steps for reproduction

Start Nitrokey app with Librem Key inserted.

#### Preconditions

N/A

#### Steps

1. Start Nitrokey app with Librem Key inserted.

### Logs

No relevant logs

**Comment by szszszsz** [comment]
Currently handled VID:PIDs in libnitrokey:
https://github.com/Nitrokey/libnitrokey/blob/28832f06f22a8e24aab4079f1f33159547704ae3/device.cc#L44-L57

**Comment by AmitAronovitch** [comment]
Added PR #163 
Does not include tests, but works for me.
(After replacing the .so with the patched version, I can successfuly run nitrokey-app on Ununtu 18.04, and use OTP with my Librem Key :-) )

**Comment by jeremiah** [comment]
Thank you all for working on this. In Purism we intend to package this and am working on it now.

**Comment by szszszsz** [comment]
Hi @jeremiah !
Could you elaborate on that?

**Comment by jeremiah** [comment]
At Purism we want our Librem Key (based on the Nitrokey) to just work out of the box so we plan to add in the relevant patches and patch Debian packages in PureOS so that things work smoothly. We'd prefer not to use a snap because of the centralized nature of snap distribution. Ideally we'd get the package patched in Debian which we will set out to do but that often is up to the Debian maintainer of course.

**Comment by kitterma** [comment]
Debian maintainer here:

I'd appreciate upstream feedback on if the addition of vendor_id results a binary incompatible change.  In Debian there are multiple libnitrokey users and I'd like to be careful not to break them.

**Comment by kitterma** [comment]
I suspect it's not binary compatible:

https://salsa.debian.org/kitterman/libnitrokey/-/merge_requests/3#note_168679

**Comment by szszszsz** [comment]
Hi! Sorry for the delay.

Indeed the API change might be not desirable. While the VID argument addition would be nice here, it should be realized as a separate function, especially when it is not required as devices can be recognized by PIDs so far.
I plan to take care of it today, and add proper support for Librem Key. This PR is long overdue, sorry for that.
@jeremiah I asked to synchronize the efforts and avoid doubling the work. Let me know is there anything besides this PR you would like to merge too.

**Comment by jeremiah** [comment]
@szszszsz Thank you very much for helping with this merge, it would likely be the best place for the work do be done since what I've done has managed to create an ABI break which might make a mess in Ubuntu and Debian. At this point I have nothing more to ask and trust in your judgement for the merge - thank you for your work on this!

**Comment by AmitAronovitch** [comment]
@szszszsz Thanks for your work and on getting this merged :tada: 

@kitterma @jeremiah  thanks for your contributions and sorry for not sharing my own packaging efforts before.
I did create a deb at the time - which works well for my personal usage ever since - but had some issues with the symbols and did not feel confident enough (and it was before release of 3.6).

In case it is of any interest: https://salsa.debian.org/amit-guest/libnitrokey/-/compare/3af0eba...master

Anyways, waiting for 3.6 to reach debian testing, so I will not have to build my own deb anymore :smiley:

**Comment by szszszsz** [comment]
@AmitAronovitch Regarding Debian Testing, hopefully we will get to this point this month.
