### ISSUE TITLE
GNU Lesser General Public License

### ISSUE THREAD

**Issue by phodina** [Nitrokey/libnitrokey#211]
Hi,
I'm packaging this library for GNU Guix and there has come up a question about the license.

There is a change in license in commit https://github.com/Nitrokey/libnitrokey/commit/c29d72a7b48cfd2899c8fd588c4ec9c12ad11e7c from GPL3+ to LGPL3+. The license also states it applies for any later version

However, in README.md you also specify in that commit just LGPL3. Is this just missing the "and later" or do you mean just this specific version?

FIY I'am not a lawyer just want to clarify what's are the correct terms.

**Comment by szszszsz** [comment]
Hi!
The intention was to use `LGPL3`. I do not see in the license text, that assumption is to use newer versions by default. Can you show it? I only see, that not declaring the license version allows to choose any of the ever published versions.

@jans23 Please let me know, if you would like to use `LGPL3 and later` instead of the `LGPL3`.

**Comment by szszszsz** [comment]
Resolving with `LGPL-3.0-only` set. Feel free to write here in case of any further questions.
Closing as done.
