### ISSUE TITLE
Remove matrix password

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/libnitrokey#3]
- remove matrix password from library and cross check with NK Storage firmware

**Comment by LukOls** [comment]
Why has this functionality been removed? Are there any plans to add it in future?

**Comment by jans23** [comment]
The reason is, that this feature is conceptionally poor. It doesn't provide significant better protection of the PIN than other schemes which are much easier to use. No plans to add something like this in the future.

**Comment by LukOls** [comment]
Thank you for your reply. For my, as well as others who might find this
thread looking for information about this feature benefit, could you reply
what other similar or dissimilar PIN protection schemes are available with
Nitro Key? There is no documentation about it at the moment and if there is
some plugin, or a fork that fulfils similar need to the one removed I'm
very interested in finding it. I specifically mean PIN protection in a
situation where the owner is forced to unlock the device, but there is no
demand to disclose the PIN. Having the ability to unlock the device while
retaining some level of control over the process may be very advantageous
especially against a non-technically sophisticated attacker.

**Comment by jans23** [comment]
The "other schemes" I mentioned are not implemented in Nitrokey. For instance some banks use a scheme where for each login the user has to enter just a subset of the PIN. Say the PIN is 8 digits long and the bank asks for 3 randomly chosen digits. This protects against observers who would need to observer several logins in order to recover the entire PIN.

Regarding the "forced to unlock" scenario: Hidden volumes are a possibility to protect you and your data in such situations.

**Comment by szszszsz** [comment]
Not present in implementation, and removed from Nitrokey Storage since the previous release. Closing as done.
